# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageviewWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageviewWindow(object):
    def setupUi(self, ImageviewWindow):
        ImageviewWindow.setObjectName("ImageviewWindow")
        ImageviewWindow.resize(500, 500)
        self.centralwidget = QtWidgets.QWidget(ImageviewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(0, 9, 500, 491))
        self.image_label.setAutoFillBackground(True)
        self.image_label.setText("")
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        ImageviewWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ImageviewWindow)
        QtCore.QMetaObject.connectSlotsByName(ImageviewWindow)

    def retranslateUi(self, ImageviewWindow):
        _translate = QtCore.QCoreApplication.translate
        ImageviewWindow.setWindowTitle(_translate("ImageviewWindow", "MainWindow"))
